[package]
name = "photon"
version = "0.1.0"
authors = ["Pavel Sergeev <pavel.sergeev@jetbrains.com>"]
edition = "2018"

[dependencies]
glutin = "0.19.0"
gleam = "0.6.8"

[dependencies.webrender]
git = "https://github.com/servo/webrender"
rev = "f7169e705ffdb335b7b994b31acd511179def8b2"